---
# baseURL needs to be the real location of the system if it is / then it will
# baseURL: "https://netdron.es" # for some reason netlify does not like the .es
# domains
baseURL: "https://netdrones.ai"
languageCode: en-us
title: NetDrones.ai
module:
  mounts:
  - source: static
    target: static
    # there is a bug as of Feb 2021 where if you mount below static, you
    # need to explicitly override it here otherwise the exampleSite mount does
    # not take
  - source: static/images
    target: static/images
  imports:
  - path: github.com/themefisher/parsa-hugo
    mounts:
    - source: layouts
      target: layouts
    - source: assets
      target: assets
    - source: static
      target: static
    - source: exampleSite/static/images
      target: static/images
# Number of words in the front page summary
summaryLength: "20"
# Note that in layout 2, if paginate is less than the
# number of type=page, then the lower image rotation fails
paginate: "5"
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/themify-icons/themify-icons.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/headroom/headroom.js
    - link: plugins/instafeed/instafeed.min.js
    - link: plugins/masonry/masonry.js
    - link: plugins/reading-time/readingTime.min.js
    - link: plugins/smooth-scroll/smooth-scroll.js
    - link: plugins/search/fuse.min.js
    - link: plugins/search/mark.js
    - link: plugins/search/search.js
  logo: images/noun_Drone_1764693_64x64.png
  home: Home
  # Note that with Layout = 2, only posts are shown and featured is hidden
  # With layout 1, the feature appears in a rotating gallery above the others.
  layout: "2"
  description: NetDrones
  preloader: true
  search: true
  author: NetDrones.ai
  author_image: images/andre-benz-BjdLaT-_rNE-unsplash_640x480.png
  bio: |
    NetDrones.ai&trade;
    is leading edge software company leading the way in artificial intelligence,
    robotics, cloud services and the decentralized application world.
  mobile: 858-848-9029
  email: info@netdrones.ai
  address: 1536 3rd St Kirkland WA 98033
  contact_form_action: "#"
  google_analitycs_id: Your ID
  copyright: Copyright &copy; 2021 NetDrones.ai&trade;, Inc. Theme by [themefisher.com](https://themefisher.com)
  # puts an instagram feed at the bottom, need an access token
  instafeed:
    enable: false
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  social:
  - icon: ti-facebook
    URL: https://facebook.com/netdrones0
  - icon: ti-twitter-alt
    URL: https://twitter.com/netdrones0
  - icon: ti-linkedin
    URL: https://linkedin.com/company/netdrones
  - icon: ti-github
    URL: https://github.com/netdrones
menu:
  main:
    - name: Home
      url: ''
      weight: 1
    # the placeholders for how to do submenus
      #hasChildren: true
    # How to link pages to the submenus
    #- parent: Homepage
    #  name: Homepage 1
    #  This uses the layout field to change the homepage layout
    #  url: homepage/home-1
    #- parent: Homepage
    #  name: Homepage 2
    #  url: homepage/home-2
    - name: About
      URL: about
      weight: "2"
    - name: Contact
      URL: contact
      weight: "3"
